package com.example.finalprojectwizelinecryptocurrencies.utils

import com.example.finalprojectwizelinecryptocurrencies.R

const val BASE_URL = "https://api.bitso.com/v3/"

val ICON_BOOK = mapOf(
    "btc" to R.drawable.ic_btc,
    "eth" to R.drawable.ic_eth,
    "xrp" to R.drawable.ic_xrp,
    "ltc" to R.drawable.ic_ltc,
    "bch" to R.drawable.ic_bch,
    "tusd" to R.drawable.ic_tusd,
    "mana" to R.drawable.ic_mana,
    "bat" to R.drawable.ic_bat,
    "dai" to R.drawable.ic_dai,
    "usd" to R.drawable.ic_usd,
    "matic" to R.drawable.ic_matic,
    "shib" to R.drawable.ic_shib,
    "usdt" to R.drawable.ic_usdt,
    "chz" to R.drawable.ic_chz,
    "doge" to R.drawable.ic_doge,
    "sol" to R.drawable.ic_sol,
    "ada" to R.drawable.ic_ada,
    "comp" to R.drawable.ic_comp,
    "link" to R.drawable.ic_link,
    "uni" to R.drawable.ic_uni,
    "aave" to R.drawable.ic_aave,
    "axs" to R.drawable.ic_axs,
    "dydx" to R.drawable.ic_dydx,
    "yfi" to R.drawable.ic_yfi,
    "sand" to R.drawable.ic_sand,
    "snx" to R.drawable.ic_snx,
    "mkr" to R.drawable.ic_mkr,
    "enj" to R.drawable.ic_enj,
    "ftm" to R.drawable.ic_ftm,
    "crv" to R.drawable.ic_crv,
    "gala" to R.drawable.ic_gala,
    "lrc" to R.drawable.ic_lrc,
    "grt" to R.drawable.ic_grt,
    "ape" to R.drawable.ic_ape,
    "sushi" to R.drawable.ic_sushi,
    "omg" to R.drawable.ic_omg,
    "dot" to R.drawable.ic_dot,
    "qnt" to R.drawable.ic_qnt,
    "bal" to R.drawable.ic_bal,
    "trx" to R.drawable.ic_trx,
    "algo" to R.drawable.ic_algo,
    "ldo" to R.drawable.ic_ldo,
    "xlm" to R.drawable.ic_xlm,
    "paxg" to R.drawable.ic_paxg
)

val NAME_BOOK = mapOf(
    "btc" to "Bitcoin",
    "eth" to "Ethereum",
    "xrp" to "XRP",
    "ltc" to "Litecoin",
    "bch" to "Bitcoin Cash",
    "tusd" to "TrueUSD",
    "mana" to "Decentraland",
    "bat" to "Basic Attention Token",
    "dai" to "Dai",
    "usd" to "USD",
    "matic" to "Polygon",
    "shib" to "Shiba Inu",
    "usdt" to "Tether",
    "chz" to "Chiliz",
    "doge" to "Dogecoin",
    "sol" to "Solana",
    "ada" to "Cardano",
    "comp" to "Compound",
    "link" to "Chainlink",
    "uni" to "Uniswap",
    "aave" to "Aave",
    "axs" to "Axie Infinity",
    "dydx" to "dYdX",
    "yfi" to "yearn.finance",
    "sand" to "The Sandbox",
    "snx" to "Synthetix",
    "mkr" to "Maker",
    "enj" to "Enjin Coin",
    "ftm" to "Fantom",
    "crv" to "Curve DAO Token",
    "gala" to "Gala",
    "lrc" to "Loopring",
    "grt" to "The Graph",
    "ape" to "ApeCoin",
    "sushi" to "SushiSwap",
    "omg" to "OMG Network",
    "dot" to "Polkadot",
    "qnt" to "Quant",
    "bal" to "Balancer",
    "trx" to "TRON",
    "algo" to "Algorand",
    "ldo" to "Lido DAO",
    "xlm" to "Stellar",
    "paxg" to "PAX Gold"
)
